
package motobazar.view;

import javax.swing.JOptionPane;
import motobazar.controller.ObradaOperater;
import motobazar.util.HibernateUtil;
import org.hibernate.Session;


public class SplashScreen extends javax.swing.JFrame {

    
    public SplashScreen() {
        initComponents();
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ucitaj() {
        new Ucitanje().start();
    }
    private class Ucitanje extends Thread{

        @Override
        public void run() {
            Session s = HibernateUtil.getSession();
            if(!s.getMetamodel().getEntities().isEmpty()){
                ObradaOperater op = new ObradaOperater();
                if(op.read().isEmpty()){
                    op.unosAdminOperatera();
                    
                }
                new ProzorLogin().setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(getRootPane(), "Problem s bazom podataka");
            }
           
        }
    }

    /**
     * @param args the command line arguments
     */
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

